### ISSUE TITLE
Questions for Magnus

### ISSUE THREAD

**Issue by markdturner** [ATNU/sarum-hymnal#1]
- [x] What format are the current digitized scores in?
- [x] Are there any scores available in TEI yet?
- [x] Is any other media material available? (Images, Videos etc)
- [x] Is there project background or copy available? (Project proposals, papers etc)
- [x] How critical is mobile support? We always make sites responsive but need to investigate how TEI scores will play on mobile. Tablets should be fine.

**Comment by tiagosousagarcia** [comment]
Hello all -- so we've just came back from seeing Magnus. Here's the gist:

-- For the first stage of the project, all Magnus needs is an image viewer with a side-bar for navigation between different hymns. However, in the future, he would like to have the possibility of viewing both other images and transcriptions in parallel, something like: Manuscript Image |  Print Image | Transcription in MEI.

-- Image format: both in jpg (96 dpi, 300 dpi) and tiff. I have access to them, let me know how you want me to send them to you. The permissions are not secured yet, but Magnus thinks he will be able to get them soon and shouldn't be a problem.

-- There's no transcriptions yet, in any format.

-- There's no additional media either

-- Copy: there's some project proposals and documentation available, but for now Magnus wants to keep it as simple as possible, literally just the image viewer and maybe a landing/about page.

-- Mobile will be important, but mostly from tablet size up -- Magnus anticipates musicians using it as if they were using a printed score, i.e., playing directly from the page, rather than printing it out. So particularly for a tablet-size, it would be good to get a cleaner interface, that maximizes the space for the music notation rather than navigation.

-- We've also asked him about the visual aspect / layout of the page, but he has no strong feelings about it. He prefers a darker background for the image viewer, and likes the functionality of MDZ (for example http://daten.digitale-sammlungen.de/~db/0010/bsb00108654/images/) and Gallica (for ex. http://gallica.bnf.fr/ark:/12148/bpt6k5811434p/f138.image.r)

Essentially, he wants something very simple to start with, but something that can be added to later on. Anything I forgot / you want to add @jamescummings ?

**Comment by markdturner** [comment]
@tiagosousagarcia thanks for all the feedback. Are you able to transfer all the images to us, please? If you can zip them all up and use [wetransfer](https://wetransfer.com/) that's probably the easiest way. If the files are over 2Gb then I'll come over with a USB drive.

**Comment by jamescummings** [comment]
I'd add that while these MS Image, Print Image, Rendered MEI (using something like Verovio) parallel panes are separate objects there will need **eventually** to be interaction between them (e.g. hover on this bit of text, the image highlights those coordinates; click on this bit of the image and text embedded in the MEI pops up with that annotation, etc.)  The MEI and TEI provide ways to store this information that we can use. 

Each pane should be browsable, collapsible, maximisable, etc. independently to enable maximum flexibility.

The coordinating principle is likely to be date in the liturgical calendar. i.e. on $dateX this particular $HymnY was used. That equates to $folioZ in the manuscript images (which is $fileA) and $pageB in the printed images (which is $fileC). But from any one of these we should be able to find any of the others. i.e. I'm on Page 24 of the printed image, what hymn is it? I want to see Hymn 54 (which will have a name probably not a number), what folio/page is it on? etc. I've got some ideas on how to do that I think. This would form the backbone of the browsing interface browse by hymn, liturgical date, folio, page. However, he hasn't collected all this information yet though.

**Comment by markdturner** [comment]
Closing this issue as feedback has been documented and gone into the requirements for other issues
